name: deploy
on:
    push:
        branches:
            # - master
            - production
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            # - name: checkout
            #   uses: actions/checkout@v2
            # - name: docker login
            #   uses: docker/login-action@v1
            #   with:
            #       username: ${{ secrets.DOCKERHUB_USERNAME }}
            #       password: ${{ secrets.DOCKERHUB_PASSWORD }}
            # - name: build and push docker
            #   uses: docker/build-push-action@v2
            #   with:
            #       push: true
            #       tags: sbkim99/poolet:latest
            - name: install ssh key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                  name: id
                  known_hosts: ${{ secrets.EC2_SSH_PUBLIC_KEY }}
                  config: |
                      Host poolet
                        HostName 52.8.107.126
                        User ec2-user
                        IdentityFile ~/.ssh/id
            - name: ssh
              run: ssh poolet cd devops/website; make run
