name: deploy
on:
    push:
        branches:
            - master
            - production
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: setup node
              uses: actions/setup-node@v2
              with:
                  node-version: 14
            - name: install yarn
              run: npm install --global yarn
            - name: docker login
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: push docker
              run: make push-docker
